trigger:
- main

pool:
  name: Default

variables:
  ACR_NAME: rishabhacr07
  IMAGE_NAME: frontend

steps:

- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(ACR_NAME)

- script: |
    docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest ./frontend
    docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
  displayName: Build and Push Image

- script: |
    kubectl get nodes
    kubectl apply -f ks8/
  displayName: Deploy to AKS
