trigger:
- main

pool:
  name: Default

variables:
  ACR_NAME: rishabhacr07
  IMAGE_NAME_FRONTEND: frontend
  IMAGE_NAME_BACKEND: backend
  TAG: $(Build.BuildId)

stages:

# 🔹 STAGE 1: BUILD & PUSH
- stage: BuildAndPush
  displayName: Build and Push Images
  jobs:
  - job: DockerJob
    steps:
    - checkout: self

    - script: |
        echo $(ACR_PASSWORD) | docker login $(ACR_NAME).azurecr.io -u $(ACR_NAME) --password-stdin
      displayName: Login to ACR

    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME_FRONTEND):$(TAG) ./frontend
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME_FRONTEND):$(TAG)
      displayName: Build & Push Frontend

    - script: |
        docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME_BACKEND):$(TAG) ./backend
        docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME_BACKEND):$(TAG)
      displayName: Build & Push Backend


# 🔹 STAGE 2: DEPLOY TO DEV (APPROVAL REQUIRED)
- stage: Deploy_Dev
  displayName: Deploy to DEV
  dependsOn: BuildAndPush

  jobs:
  - deployment: DevDeploy
    environment: dev   # 👈 MUST MATCH ENV NAME
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - script: kubectl get nodes
            displayName: Check AKS

          - script: |
              kubectl set image deployment/ecommerce-frontend \
              frontend=$(ACR_NAME).azurecr.io/$(IMAGE_NAME_FRONTEND):$(TAG)

              kubectl set image deployment/ecommerce-backend \
              backend=$(ACR_NAME).azurecr.io/$(IMAGE_NAME_BACKEND):$(TAG)
            displayName: Update Images

          - script: kubectl apply -f ks8/
            displayName: Apply YAML

          - script: kubectl rollout status deployment/ecommerce-frontend
            displayName: Verify Frontend

          - script: kubectl rollout status deployment/ecommerce-backend
            displayName: Verify Backend


# 🔹 STAGE 3: DEPLOY TO PROD (APPROVAL REQUIRED)
- stage: Deploy_Prod
  displayName: Deploy to PROD
  dependsOn: Deploy_Dev

  jobs:
  - deployment: ProdDeploy
    environment: production   # 👈 MUST MATCH EXACT NAME
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self

          - script: kubectl get nodes
            displayName: Check AKS

          - script: |
              kubectl set image deployment/ecommerce-frontend \
              frontend=$(ACR_NAME).azurecr.io/$(IMAGE_NAME_FRONTEND):$(TAG)

              kubectl set image deployment/ecommerce-backend \
              backend=$(ACR_NAME).azurecr.io/$(IMAGE_NAME_BACKEND):$(TAG)
            displayName: Update Images

          - script: kubectl apply -f ks8/
            displayName: Apply YAML

          - script: kubectl rollout status deployment/ecommerce-frontend
            displayName: Verify Frontend

          - script: kubectl rollout status deployment/ecommerce-backend
            displayName: Verify Backend