trigger:
- main

pool:
  name: Default

variables:
  ACR_NAME: rishabhacr07
  IMAGE_NAME: frontend

steps:

- checkout: self

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name $(ACR_NAME)

- script: |
    docker build -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) ./frontend
    docker tag $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId) $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
    docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(Build.BuildId)
    docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):latest
  displayName: Build and Push Image

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azure-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az aks get-credentials \
        --name ecommerce-aks \
        --resource-group ecommerseapp \
        --overwrite-existing

- script: |
    kubectl apply -f ks8/
  displayName: Deploy to AKS
