apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  ingressClassName: azure-application-gateway

  tls:
  - hosts:
    - rishabhpathak.me
    - www.rishabhpathak.me
    secretName: ecommerce-tls

  rules:
  - host: rishabhpathak.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecommerce-frontend
            port:
              number: 80

  - host: www.rishabhpathak.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ecommerce-frontend
            port:
              number: 80
